services:
  postgres:
    image: "bitnami/postgresql:latest"
    container_name: petshop-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nasa_db
